name: ASP.NET CI

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
       { curl https://api.github.com/repos/mangeshpa/simple-java-maven-app/commits | jq '.[] | {commitid: .sha, date: .commit.author.date, commitauthor: .commit.author.name}'\ &&
       curl -X GET https://api.github.com/repos/mangeshpa/simple-java-maven-app/commits | grep -w sha; } >> "./output.json"
       #curl -X GET https://api.github.com/repos/mangeshpa/simple-java-maven-app/repo | grep -w name >> "./output.json"

    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./output.json
