name: ASP.NET CI
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
       curl --header "PRIVATE-TOKEN: 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" "https://gitlab.example.com/api/v4/projects/5/repository/commits/master"       
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./output.json
