name: ASP.NET CI
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
       curl -H "Accept: application/vnd.github.v3+json" \https://github.com/mangeshpa/simple-java-maven-app/commits?state=open  -o "./output.json"
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./output.json
