name: ASP.NET CI
on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
       curl -X GET -u mangeshpa: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 https://api.github.com/repos/mangeshpa/simple-java-maven-app/pulls?state=open  -o "./output.json"
      
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./output.json
